# @format

AWSTemplateFormatVersion: 2010-09-09

Resources:
  ProjectFrontendEcommLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/frontend-ecomm-task
      RetentionInDays: 1

  ProjectFullStackECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: fullstack-ecomm-service
      Cluster: !ImportValue ECSCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !ImportValue TaskDefinition
      LoadBalancers:
        - ContainerName: project-frontend-ecomm-container
          ContainerPort: 3002
          TargetGroupArn: !ImportValue ProjectFrontendEcommTargetGroupArn

        - ContainerName: project-backend-ecomm-container
          ContainerPort: 4000
          TargetGroupArn: !ImportValue ProjectBackendEcommTargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue TaskSecurityGroup
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0

Outputs:
  ProjectFullStackECSServiceName:
    Value: !Ref ProjectFullStackECSService
    Export:
      Name: ProjectFullStackECSServiceName
