# @format

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Region:
    Type: String
  ECSClusterNameParam:
    Type: String
  ECSServiceNameParam:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterNameParam

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/portfolio-task
      RetentionInDays: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: portfolio-task
      Cpu: 512
      Memory: 1024
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge #Changed from awsvpc to bridge
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: app-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/portfolio-dev:latest"
          Cpu: 512
          MemoryReservation: 1024
          Essential: true
          PortMappings:
            - ContainerPort: 80
              HostPort: 8080 #Explicit host port
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/portfolio-task
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inboud access to ECS tasks
      VpcId: !ImportValue VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3002
          ToPort: 3002
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 4000
          ToPort: 4000
          CidrIp: 0.0.0.0/0

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ECSServiceNameParam
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: app-container
          ContainerPort: 80
          TargetGroupArn: !ImportValue TargetGroupArn
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0

Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: ECSClusterName

  ECSServiceName:
    Value: !Ref ECSServiceNameParam
    Export:
      Name: ECSServiceName

  TaskExecutionRoleArn:
    Description: ARN of the ECS task execution role
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: TaskExecutionRoleArn

  TaskSecurityGroup:
    Value: !Ref TaskSecurityGroup
    Export:
      Name: TaskSecurityGroup

  TaskDefinitionName:
    Value: !Ref TaskDefinition
    Export:
      Name: TaskDefinitionName

  ForceUpdate:
    Description: Dummy output to force stack update
    Value: "1"
