# @format

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Region:
    Type: String
  ECSClusterNameParam:
    Type: String
  ECSServiceNameParam:
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/portfolio-task
      RetentionInDays: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: portfolio-task
      Cpu: 256
      Memory: 512
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge #Changed from awsvpc to bridge
      ExecutionRoleArn: !ImportValue TaskExecutionRoleArn
      ContainerDefinitions:
        - Name: app-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/portfolio-dev:latest"
          Cpu: 256
          MemoryReservation: 512
          Essential: true
          PortMappings:
            - ContainerPort: 80
              HostPort: 8080 #Explicit host port
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/portfolio-task
              awslogs-region: !Ref Region
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ECSServiceNameParam
      Cluster: !ImportValue ECSClusterName
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: app-container
          ContainerPort: 80
          TargetGroupArn: !ImportValue TargetGroupArn
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0

Outputs:
  ECSServiceName:
    Value: !Ref ECSService
    Export:
      Name: ECSServiceName
