# @format

Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - !ImportValue PublicSubnet1
        - !ImportValue PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !ImportValue LaunchTemplateId
        Version: !ImportValue LaunchTemplateVersion
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: ECSInstance
          PropagateAtLaunch: true
        - Key: AmazonECSManaged
          Value: "true"
          PropagateAtLaunch: true
