# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Route 53 alias record for ALB

Parameters:
  RootDomainName:
    Type: String
    Description: The root domain
  WWWDomainName:
    Type: String
    Description: The www subdomain
  Project1Domain:
    Type: String
  Project2Domain:
    Type: String
  ProjectFrontendEcommDomain:
    Type: String
  ProjectBackendEcommDomain:
    Type: String
  HostedZoneId:
    Type: String
    Description: The ID of the Route 53 hosted zone

Resources:
  # A record for www.lamounierdigital.com
  Route53AliasRecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref WWWDomainName
      Type: A
      AliasTarget:
        DNSName: !ImportValue LoadBalancerDNS
        HostedZoneId: !ImportValue LoadBalancerHostedZoneId

  # A record for lamounierdigital.com (root domain)
  Route53AliasRecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RootDomainName
      Type: A
      AliasTarget:
        DNSName: !ImportValue LoadBalancerDNS
        HostedZoneId: !ImportValue LoadBalancerHostedZoneId

  # A record for project1.lamounierdigital.com
  Project1DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Project1Domain
      Type: A
      AliasTarget:
        DNSName: !ImportValue LoadBalancerDNS
        HostedZoneId: !ImportValue LoadBalancerHostedZoneId

    # A record for project2.lamounierdigital.com
  Project2DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Project2Domain
      Type: A
      AliasTarget:
        DNSName: !ImportValue LoadBalancerDNS
        HostedZoneId: !ImportValue LoadBalancerHostedZoneId

    # A record for project3.lamounierdigital.com
  ProjectFrontendEcommDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ProjectFrontendEcommDomain
      Type: A
      AliasTarget:
        DNSName: !ImportValue LoadBalancerDNS
        HostedZoneId: !ImportValue LoadBalancerHostedZoneId

    # A record for api.lamounierdigital.com
  ProjectFrontendEcommDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ProjectBackendEcommDomain
      Type: A
      AliasTarget:
        DNSName: !ImportValue LoadBalancerDNS
        HostedZoneId: !ImportValue LoadBalancerHostedZoneId

  
