# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Master Nested Stack to deploy portfolio infrastructure components

# Parameters:
#   # SSLCertificateArn:
#   #   Type: String
#   #   Description: ARN of the ACM SSL certificate to use for HTTPS

Resources:
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and HTTPS access
      VpcId: !ImportValue VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: PortfolioALB
      Subnets:
        - !ImportValue PublicSubnet1
        - !ImportValue PublicSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSG
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue VPC
      TargetType: instance
      HealthCheckPath: /healthcheck
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200

  Project1TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: project1-target-group
      VpcId: !ImportValue VPC
      Protocol: HTTP
      Port: 3000
      TargetType: instance
      HealthCheckPath: /api/healthcheck
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200

  Project2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: project2-target-group
      VpcId: !ImportValue VPC
      Protocol: HTTP
      Port: 3001
      TargetType: instance
      HealthCheckPath: /index.html
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200

  ProjectFrontendEcommTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: project-frontend-tg
      VpcId: !ImportValue VPC
      Protocol: HTTP
      Port: 3002
      TargetType: instance
      HealthCheckPath: /healthcheck
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200

  ProjectBackendEcommTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: project-backend-tg
      VpcId: !ImportValue VPC
      Protocol: HTTP
      Port: 4000
      TargetType: instance
      HealthCheckPath: /healthcheck
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !ImportValue SSLCertificateArn
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404
            ContentType: text/plain
            MessageBody: "No matching host rule found"

  PortfolioListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 10
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - lamounierdigital.com
              - www.lamounierdigital.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  Project1ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 20
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - project1.lamounierdigital.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref Project1TargetGroup

  Project2ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 30
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - project2.lamounierdigital.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref Project2TargetGroup

  ProjectFrontendEcommListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 40
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - project3.lamounierdigital.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ProjectFrontendEcommTargetGroup

  ProjectBackendEcommListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 50
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - api.lamounierdigital.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ProjectBackendEcommTargetGroup

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ALB.DNSName
    Export:
      Name: LoadBalancerDNS

  LoadBalancerHostedZoneId:
    Description: Hosted zone ID for the Application Load Balancer
    Value: !GetAtt ALB.CanonicalHostedZoneID
    Export:
      Name: LoadBalancerHostedZoneId

  TargetGroupArn:
    Description: The ARN of the ALB target group
    Value: !Ref TargetGroup
    Export:
      Name: TargetGroupArn

  Project1TargetGroupArn:
    Description: Target Group ARN for project1
    Value: !Ref Project1TargetGroup
    Export:
      Name: Project1TargetGroupArn

  Project2TargetGroupArn:
    Description: Target Group ARN for project2
    Value: !Ref Project2TargetGroup
    Export:
      Name: Project2TargetGroupArn

  ProjectFrontendEcommTargetGroupArn:
    Description: Target Group ARN for project3(Frontend ecommerce application)
    Value: !Ref ProjectFrontendEcommTargetGroup
    Export:
      Name: ProjectFrontendEcommTargetGroupArn

  ProjectBackendEcommTargetGroupArn:
    Description: Target Group ARN for backend ecommerce application
    Value: !Ref ProjectBackendEcommTargetGroup
    Export:
      Name: ProjectBackendEcommTargetGroupArn
