# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Master Nested Stack to deploy portfolio infrastructure components

Parameters:
  TemplateBucket:
    Type: String
    Description: S3 Bucket containing the nested templates
  TemplatePrefix:
    Type: String
    Description: Optional prefix (Folder) in the bucket (e.g., "infra/")
  ArtifactBucket:
    Type: String
    Description: The S3 bucket used to store build artifacts
  ECSCluster:
    Type: String
    Description: The ECSCluster used on the Launch Template
  ECSServiceNameParam:
    Type: String
  ECSClusterNameParam:
    Type: String
  Region:
    Type: String
  SSLCertificateArn:
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}VPC.yml

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}LoadBalancer.yml
      Parameters:
        SSLCertificateArn: !Ref SSLCertificateArn

  LaunchTemplateStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}LaunchTemplate.yml
      Parameters:
        ECSCluster: !Ref ECSCluster
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1

  ServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoadBalancerStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}Service.yml
      Parameters:
        ECSServiceNameParam: !Ref ECSServiceNameParam
        ECSClusterNameParam: !Ref ECSClusterNameParam
        Region: !Ref Region

  # Project1ServiceStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - LoadBalancerStack
  #     - ServiceStack
  #   Properties:
  #     TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}Project1Service.yml
  #     Parameters:
  #       ECSServiceNameParam: project1-service
  #       ECSClusterNameParam: !Ref ECSClusterNameParam
  #       Region: !Ref Region

  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LaunchTemplateStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}AutoScalingGroup.yml

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ServiceStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}DeploymentPipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  Project1PipelineStackV3:
    Type: AWS::CloudFormation::Stack
    DependsOn: ServiceStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}Project1Pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        Project1ServiceName: !Ref ECSServiceNameParam
