# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Master Nested Stack to deploy portfolio infrastructure components

Mappings:
  TagMap:
    dev:
      Project: Portfolio
      Owner: Nelson
      CreatedBy: CloudFormation
      CostCenter: DevTeam
    prod:
      Project: Portfolio
      Owner: Nelson
      CreatedBy: CloudFormation
      CostCenter: Production

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev
    Description: Deployment environment (dev or prod)

  TemplateBucket:
    Type: String
    Description: S3 Bucket containing the nested templates
  TemplatePrefix:
    Type: String
    Description: Folder path
  ArtifactBucket:
    Type: String
    Description: The S3 bucket used to store build artifacts
  ECSCluster:
    Type: String
    Description: The ECSCluster used on the Launch Template
  ECSClusterNameParam:
    Type: String
  Region:
    Type: String
  RootDomainName:
    Type: String
  WWWDomainName:
    Type: String
  Project1Domain:
    Type: String
  Project2Domain:
    Type: String
  ProjectFrontendEcommDomain:
    Type: String
  ProjectBackendEcommDomain:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}VPC.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - CertificateStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}LoadBalancer.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment

  LaunchTemplateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}LaunchTemplate.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ECSCluster: !Ref ECSCluster
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1

  ServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoadBalancerStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}services/Service.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ECSServiceNameParam: portfolio-service
        ECSClusterNameParam: !Ref ECSClusterNameParam
        Region: !Ref Region

  Project1ServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}services/Project1Service.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ECSServiceNameParam: project1-service
        ECSClusterNameParam: !Ref ECSClusterNameParam
        Region: !Ref Region

  Project2ServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}services/Project2Service.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ECSServiceNameParam: project2-service
        ECSClusterNameParam: !Ref ECSClusterNameParam
        Region: !Ref Region

  ProjectFullStackServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}services/ProjectFullStackService.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ECSServiceNameParam: ecom-fullstack-service
        ECSClusterNameParam: !Ref ECSClusterNameParam
        Region: !Ref Region

  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LaunchTemplateStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}AutoScalingGroup.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment

  DNSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoadBalancerStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}dns.yml
      Parameters:
        RootDomainName: !Ref RootDomainName
        WWWDomainName: !Ref WWWDomainName
        Project1Domain: !Ref Project1Domain
        Project2Domain: !Ref Project2Domain
        ProjectFrontendEcommDomain: !Ref ProjectFrontendEcommDomain
        ProjectBackendEcommDomain: !Ref ProjectBackendEcommDomain
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment

  CertificateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}certificate.yml
      Parameters:
        RootDomainName: !Ref RootDomainName
        WWWDomainName: !Ref WWWDomainName
        Project1DomainName: !Ref Project1Domain
        Project2DomainName: !Ref Project2Domain
        ProjectFEDomainName: !Ref ProjectFrontendEcommDomain
        ProjectBEDomainName: !Ref ProjectBackendEcommDomain
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ServiceStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}pipelines/DeploymentPipeline.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  Project1PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}pipelines/Project1Pipeline.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        Project1ServiceName: !GetAtt Project1ServiceStack.Outputs.Project1ECSServiceName

  Project2PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}pipelines/Project2Pipeline.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        Project2ServiceName: !GetAtt Project2ServiceStack.Outputs.Project2ECSServiceName

  Project3PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}pipelines/Project3Pipeline.yml
      Tags:
        - Key: Project
          Value: !FindInMap [TagMap, !Ref Environment, Project]
        - Key: Owner
          Value: !FindInMap [TagMap, !Ref Environment, Owner]
        - Key: CreatedBy
          Value: !FindInMap [TagMap, !Ref Environment, CreatedBy]
        - Key: CostCenter
          Value: !FindInMap [TagMap, !Ref Environment, CostCenter]
        - Key: Environment
          Value: !Ref Environment
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        ProjectEcommServiceName: !GetAtt ProjectFullStackServiceStack.Outputs.ProjectFullStackECSServiceName
