# @format

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Region:
    Type: String
  ECSClusterNameParam:
    Type: String
  ECSServiceNameParam:
    Type: String

Resources:
  Project1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/project1-task
      RetentionInDays: 1

  Project1TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: project1-task
      Cpu: 256
      Memory: 1024
      RequiresCompatibilities:
        - EC2
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue TaskExecutionRoleArn
      ContainerDefinitions:
        - Name: project1-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/project1-dev:latest"
          Cpu: 256
          Memory: 1024
          MemoryReservation: 512
          Essential: true
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/project1-task
              awslogs-region: !Ref Region
              awslogs-stream-prefix: ecs

  Project1ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ECSServiceNameParam
      Cluster: !Ref ECSClusterNameParam
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref Project1TaskDefinition
      LoadBalancers:
        - ContainerName: project1-container
          ContainerPort: 80
          TargetGroupArn: !ImportValue Project1TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue TaskSecurityGroup
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180

Outputs:
  Project1ServiceName:
    Value: !Ref ECSServiceNameParam
    Export:
      Name: Project1ServiceName
