# @format

AWSTemplateFormatVersion: 2010-09-09

Resources:
  Project2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/project2-task
      RetentionInDays: 1

  Project2ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: project2-service
      Cluster: !ImportValue ECSCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !ImportValue TaskDefinition
      LoadBalancers:
        - ContainerName: project2-container
          ContainerPort: 3001
          TargetGroupArn: !ImportValue Project2TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue TaskSecurityGroup
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0

Outputs:
  Project2ECSServiceName:
    Value: !Ref Project2ECSService
    Export:
      Name: Project2ECSServiceName
