# @format

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Region:
    Type: String
  ECSClusterNameParam:
    Type: String
  ECSServiceNameParam:
    Type: String

Resources:
  Project1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/project1-task-${AWS::StackName}
      RetentionInDays: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: project1-task
      Cpu: 128
      Memory: 256
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge # Changed from awsvpc to bridge
      ExecutionRoleArn: !ImportValue TaskExecutionRoleArn
      ContainerDefinitions:
        - Name: project1-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/project1-dev:latest"
          Cpu: 128
          MemoryReservation: 256
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000 #  Explicit HostPort to match ALB TargetGroup
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/project1-task-${AWS::StackName}
              awslogs-region: !Ref Region
              awslogs-stream-prefix: ecs

  Project1ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ECSServiceNameParam
      Cluster: !ImportValue ECSClusterName
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: project1-container
          ContainerPort: 3000
          TargetGroupArn: !ImportValue Project1TargetGroupArn
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0

Outputs:
  Project1ECSServiceName:
    Value: !Ref Project1ECSService
    Export:
      Name: Project1ECSServiceName
