# @format

AWSTemplateFormatVersion: 2010-09-09

Resources:
  Project1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/project1-task
      RetentionInDays: 1

  Project1ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: project1-service
      Cluster: !ImportValue ECSCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !ImportValue TaskDefinition
      LoadBalancers:
        - ContainerName: project1-container
          ContainerPort: 3000
          TargetGroupArn: !ImportValue Project1TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue TaskSecurityGroup
      EnableECSManagedTags: true
      DeploymentController:
        Type: ECS
      HealthCheckGracePeriodSeconds: 180
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0

Outputs:
  Project1ECSServiceName:
    Value: !Ref Project1ECSService
    Export:
      Name: Project1ECSServiceName
