Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: portfolio

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: PortfolioCluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: portfolio-task
      Cpu: 256
      Memory: 512
      RequiresCompatibilies:
        - EC2
      NetworkMode: bridge
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: app-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/portfolio:lastest"
          Memory: 512
          PortMapping:
            - ContainerPort: 80

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: app-container
          ContainerPort: 80
          TargetGroupArn: !ImportValue TargetGroupArn

Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: ECSClusterName

  ECSServiceName:
    Value: !Ref ECSService
    Export:
      Name: ECSServiceName

